### ISSUE TITLE
bug report: Client Arguments field raises exception if blank

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/elastic_search#16]
```
[2016-03-15 17:23:59.592] NIO [WARNING] [FlowToES.LocalES_Insert] Client Arguments needs to be a dictionary:
Traceback (most recent call last):
  File "/home/nio/nio/projects/test/blocks/elastic_search/es_base_block.py", line 69, in _build_elasticsearch_client_kwargs
    client_kwargs = json.loads(client_kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hansmosh** [comment]
As a work around, set "Client Arguments" to an empty dict: `{}`

**Comment by mattdodge** [comment]
@kevincrabbe this is a good one to start with

**Comment by kevincrabbe** [comment]
Pull request got merged: https://github.com/nio-blocks/elastic_search/pull/17
